name: Run precompute and push to Hugging Face

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6:00 AM UTC
  workflow_dispatch:      # manual trigger
  push:
    branches:
      - main

jobs:
  run-precompute:
    runs-on: ubuntu-latest

    steps:
      # --- Step 1: Checkout code ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Step 2: Setup Python environment ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- Step 3: Install dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install huggingface_hub

      # --- Step 4: Run the precompute script ---
      - name: Run precompute.py
        run: |
          echo "🚀 Running precompute.py to generate FAISS index..."
          python precompute.py
          echo "✅ Finished generating FAISS index. Contents of ./db:"
          ls -lh db || echo "⚠️ db folder missing!"

      # --- Step 5: Push to Hugging Face Space ---
      - name: Push generated database to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'EOF'
          from huggingface_hub import HfApi, upload_file
          import os
      
          api = HfApi(token=os.environ["HF_TOKEN"])
          repo_id = "akanshajain231999/EvalAI-Chatbot"
          folder_path = "db"
      
          print(f"⬆️ Uploading files from {folder_path} to Hugging Face Space {repo_id} under /db/")
          for fname in os.listdir(folder_path):
              file_path = os.path.join(folder_path, fname)
              api.upload_file(
                  path_or_fileobj=file_path,
                  path_in_repo=f"db/{fname}",
                  repo_id=repo_id,
                  repo_type="space"
              )
              print(f"✅ Uploaded {fname} → /db/{fname}")
          EOF
