name: Run precompute and push to Hugging Face

on:
  schedule:
    - cron: '0 6 * * *'   # every day at 6:00 AM UTC
  workflow_dispatch:       # allow manual trigger
  push:
    branches:
      - main

jobs:
  run-precompute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install huggingface_hub  # to push files to Hugging Face

      - name: Run precompute.py
        run: |
          python precompute.py

      - name: Push generated database to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python - <<'EOF'
          from huggingface_hub import HfApi, upload_folder
          import os

          repo_id = "akanshajain231999/EvalAI-Chatbot"  # 🧠 Your actual Space ID
          folder_path = "db"  # Folder created by precompute.py

          api = HfApi(token=os.environ["HF_TOKEN"])
          upload_folder(
              folder_path=folder_path,
              repo_id=repo_id,
              repo_type="space"
          )
          print(f"✅ Uploaded folder '{folder_path}' to Hugging Face Space: {repo_id}")
          EOF
